### PR TITLE
[New Features] Quartiles styles, half violins and histograms on the side

### PR DESCRIPTION
**Pull request by mikelgg93**
This pull request includes several new features.

- Ability to plot either the right, left-half or the full violin independently of the comparison mode.
- Ability to change how quartiles are plotted, as a shadow on the violin plot, the prior boxplot or completely omit them.
- New plot data style, instead of a scatter plot, a histogram on the side.

Notes:
I did these changes before the last changes were made, therefore new features are not fully implemented with the comparison mode. However, I did ensure that these changes did not break anything, in the future, a clean-up can be made to not repeat so much how jitter is generated.

- [X] Working without including regressions.
- [X] New test added, showcasing new options.

Todo:
- [ ] Include the qStyles to the comparison mode.

For the sake of simplicity I leave here the new output from the test function:

testplot

### CODE REVIEW

**Comment by bastibe** [comment]
Thank you! This is awesome!

I would ask you however to rename the parameters vHalf, qStyles, barpltBool to match the style of the remainder of the parameters, e.g. to HalfViolin, ShowQuartiles, ShowHistogram. Also, I think scpltBool is a duplication of ShowData, and should be removed.

**Comment by mikelgg93** [comment]
> ShowQuartiles

As requested, the names of the parameters have been changed, a small clean up was also performed.
Removed the boolean parameter 'scpltBool' and 'barpltBool' in favour of 'DataStyles.

HalfViolin     - Whether to do a half violin(left, right side) or full. Defaults to full.
QuartileStyle  - Option on how to display quartiles, with a boxplot, shadow or none. Defaults to boxplot.
DataStyle      - Defines the style to show the data points. Opts: 'scatter', 'histogram' or 'none'. Default is 'scatter'.

I kept the ShowData, because of the method, now it also removes the histogram.
A new test case was added to test the ability to remove the data, after plotting it.

**Comment by bastibe** [comment]
Great work! This looks really good! Thank you so much!

Regrettably, Github doesn't show me a proper diff, and anyways I don't have access to Matlab any longer, so I can't really test your code in any meaningful way. But I'll trust you that everything works as it should. Does the original test suite still run? We don't want to break existing code.

If all of that is in order, I'll gladly merge your contribution when you say it's ready.

**Comment by mikelgg93** [comment]
Thanks to you! Yeah! I also notice that Github oddly did not show proper differences, although in VSCode it does for me... 

 _I don't have access to Matlab any longer_
That´s sad, let me know if you want me to help you maintain the repo.

And yes, the original test, still runs, in fact, the modified `testviolinplot.m` still includes the 4 original tests.
I include a screenshot of the original one (the screenshot will disappear after one day).

imageoftheoriginaltest

From my side, everything is ready so merge at your wish! Have a nice day!

**Comment by bastibe** [comment]
Perfect! If you'd like to help maintain the Violinplot, I'd be happy to have you on board!

**Comment by mikelgg93** [comment]
> Perfect! If you'd like to help maintain the Violinplot, I'd be happy to have you on board!
Count me in, I don´t think it will rob me of too much time.

**Comment by bastibe** [comment]
I've sent you an invite to become a collaborator on this repository! Thank you for your help!

**Comment by bastibe** [comment]
Would you like to add your cool new graph variants to the screenshot in the README?

**Pull request merged**
