### PR TITLE
Fix "shadow" quartiles delimiters were not perfectly horizontal

### PR DESCRIPTION
**Pull request by cellomario**
Hi there and thank you for your wonderful tool,

When using the "shadow" mode to visualize the quartile ranges, the highlighted portion of the violin was cut in a non-horizontal fashion due to an off-by-one error. I fixed that.

Old behavior:

image

New behavior:

image

### CODE REVIEW

**Review by mikelgg93 — APPROVED** [review]
I have no Matlab to test it, but the change in the code looks good, and the screenshots too! Perhaps if you have the time you could recreate the figure in the README

**Comment by mikelgg93** [comment]
This fixes #59

**Comment by cellomario** [comment]
Will do.

Do you have the script to generate it? It could be included in the repository as an usage example

**Comment by bastibe** [comment]
Wonderful! This looks much better! Thank you for the Pull Request.

Regrettably, I don't have access to Matlab any longer, either, and neither do I have the script for the README plot.

**Comment by cellomario** [comment]
Done! it's not exactly the same as I was not able to do the weird horizontal offset in the "Italy +1.5" column, and I am not familiar with the colormap you used, so I used the default one, but it's a useful starting point, feel free to modify it when you decide to merge my contributions

**Comment by cellomario** [comment]
Done! it's not exactly the same as I was not able to do the weird horizontal offset in the "Italy +1.5" column, and I am not familiar with the colormap you used, so I used the default one, but it's a useful starting point, feel free to modify it when you decide to merge my contributions

**Comment by bastibe** [comment]
Fantastic work, thank you so much!

I'll merge it when you say it's ready!

**Comment by cellomario** [comment]
Then I'd say it's ready ;)

**Pull request merged**
